(function(d){d.MovingObjectsLibrary=function(){var c={moving_object:0,mouse_offset:{},obj_coords_old:{},obj_coords_new:{},cond_mouse_move_x:!0,cond_mouse_move_y:!0,obj_parent_coords:{},cursor_coords:{},cond_mouse_move_left:!0,cond_mouse_move_top:!0,FuncMouseMove:function(){},FuncMouseDown:function(){},FuncMouseUp:function(){},FuncMouseOver:function(){},FuncMouseOut:function(){},GetPosition:function(b){for(var a=0,c=0;b.offsetParent;)a+=b.offsetLeft,c+=b.offsetTop,b=b.offsetParent;a+=b.offsetLeft;
c+=b.offsetTop;return{x:a,y:c}},FixEvent:function(b){b=b||d.event;if(null==b.pageX&&null!=b.clientX){var a=document.documentElement,c=document.body;b.pageX=b.clientX+(a&&a.scrollLeft||c&&c.scrollLeft||0)-(a.clientLeft||0);b.pageY=b.clientY+(a&&a.scrollTop||c&&c.scrollTop||0)-(a.clientTop||0)}!b.which&&b.button&&(b.which=b.button&1?1:b.button&2?3:b.button&4?2:0);return b},GetMouseOffset:function(b,a){c.obj_coords_old=c.GetPosition(b);return{x:a.pageX-c.obj_coords_old.x,y:a.pageY-c.obj_coords_old.y}},
EMouseDown:function(b){b=c.FixEvent(b);c.moving_object=this;c.mouse_offset=c.GetMouseOffset(this,b);c.obj_parent_coords=c.GetPosition(this.parentNode);document.onmousemove=c.EMouseMove;document.onmouseup=c.EMouseUp;document.ondragstart=function(){return!1};document.body.onselectstart=function(){return!1};c.FuncMouseDown();return!1},EMouseMove:function(b){b=c.FixEvent(b);c.cursor_coords={x:b.pageX,y:b.pageY};c.obj_coords_new={x:c.cursor_coords.x-c.mouse_offset.x-c.obj_parent_coords.x,y:c.cursor_coords.y-
c.mouse_offset.y-c.obj_parent_coords.y};c.FuncMouseMove();c.cond_mouse_move_x&&(c.moving_object.style.left=c.obj_coords_new.x+"px");c.cond_mouse_move_y&&(c.moving_object.style.top=c.obj_coords_new.y+"px");return!1},EMouseUp:function(){c.moving_object=null;document.onmousemove=null;document.onmouseup=null;document.ondragstart=null;document.body.onselectstart=null;c.FuncMouseUp()},EMouseOver:function(b){b=c.FixEvent(b);c.obj_parent_coords=c.GetPosition(this);document.onmousemove=c.EMouseMove;document.onmouseout=
c.EMouseOut;document.ondragstart=function(){return!1};document.body.onselectstart=function(){return!1};c.FuncMouseOver();return!1},EMouseOut:function(){document.onmousemove=null;document.onmouseout=null;document.ondragstart=null;document.body.onselectstart=null;c.FuncMouseOut()},MouseDraging:function(b){b.onmousedown=c.EMouseDown},MouseMoving:function(b,a){c.moving_object=a;b.onmouseover=c.EMouseOver},SetStyle:function(b,a){for(var c in a)b.style[c]=a[c]},SetAttributes:function(b,a){for(var c in a)setAttribute(c,
a[c])},SetParameters:function(b,a){for(var c in a)b[c]=a[c]},CreateObj:function(b,a,e){b=document.createElement(b);a.position=a&&a.position?a.position:"absolute";a.left=a&&a.left?a.left:"0px";a.top=a&&a.top?a.top:"0px";c.SetStyle(b,a);void 0!=e&&c.SetParameters(b,e);return b},ZoomMoving:function(b){var a={little_left:b&&b.little_left?b.little_left:"auto",little_top:b&&b.little_top?b.little_top:"auto",little_right:b&&b.little_right?b.little_right:"auto",little_bottom:b&&b.little_bottom?b.little_bottom:
"auto",little_width:b&&b.little_width?b.little_width:300,little_height:b&&b.little_height?b.little_height:300,little_href:b&&b.little_href?b.little_href:"",big_left:b&&b.big_left?b.big_left:350,big_top:b&&b.big_top?b.big_top:0,big_width:b&&b.big_width?b.big_width:400,big_height:b&&b.big_height?b.big_height:400,big_real_width:b&&b.big_real_width?b.big_real_width:600,big_real_height:b&&b.big_real_height?b.big_real_height:600,big_href:b&&b.big_href?b.big_href:""};a.main_obj=b&&b.main_obj?b.main_obj:
c.CreateObj("div",{position:"absolute",left:a.little_left,top:a.little_top,right:a.little_right,bottom:a.little_bottom},{id:"zoom_moving"});a.main_obj.parent_obj=a;a.little_obj=c.CreateObj("div",{position:"absolute",left:"0px",top:"0px",width:a.little_width+"px",height:a.little_height+"px",cursor:"move"});a.main_obj.appendChild(a.little_obj);a.little_img=c.CreateObj("img",{position:"static",left:"0px",top:"0px",width:a.little_width+"px",height:a.little_height+"px"},{src:a.little_href});a.little_obj.appendChild(a.little_img);
a.big_rect=c.CreateObj("div",{position:"absolute",left:a.big_left+"px",top:a.big_top+"px",width:a.big_width+"px",height:a.big_height+"px",overflow:"hidden",display:"none"});a.main_obj.appendChild(a.big_rect);a.big_img=c.CreateObj("img",{position:"absolute",left:"0px",top:"0px",width:a.big_real_width+"px",height:a.big_real_height+"px"},{src:a.big_href});a.big_rect.appendChild(a.big_img);a.rect_width=parseInt(a.big_width*a.little_width/a.big_real_width);a.rect_height=parseInt(a.big_height*a.little_height/
a.big_real_height);a.little_rect=c.CreateObj("div",{width:a.rect_width+"px",height:a.rect_height+"px",backgroundColor:"#DDD8D1",opacity:0.4,filter:"alpha(opacity=40)",display:"none"});a.little_obj.appendChild(a.little_rect);c.FuncMouseMove=function(b){c.cond_mouse_move_x=0<=c.obj_coords_new.x&&c.obj_coords_new.x<=parseInt(a.little_obj.style.width)-parseInt(a.little_rect.style.width);c.cond_mouse_move_y=0<=c.obj_coords_new.y&&c.obj_coords_new.y<=parseInt(a.little_obj.style.height)-parseInt(a.little_rect.style.height);
c.cond_mouse_move_x&&(a.big_img.style.left=parseInt(-parseInt(a.little_rect.style.left)*a.big_real_width/a.little_width)+"px");c.cond_mouse_move_y&&(a.big_img.style.top=parseInt(-parseInt(a.little_rect.style.top)*a.big_real_height/a.little_height)+"px")};c.FuncMouseOver=function(){c.mouse_offset.x=parseInt(a.rect_width/2);c.mouse_offset.y=parseInt(a.rect_height/2);a.big_rect.style.display="block";a.little_rect.style.display="block"};c.FuncMouseOut=function(){a.big_rect.style.display="none";a.little_rect.style.display=
"none"};c.MouseMoving(a.little_obj,a.little_rect);return a}};return c}})(window);