version: "3.7"

services:
  web:
    build:
      context: ./docker/images/web
    ports:
      - ${HOST_WEB_HTTP_PORT}:${DEFAULT_WEB_HTTP_PORT}
      - ${HOST_WEB_HTTPS_PORT}:${DEFAULT_WEB_HTTPS_PORT}
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
    depends_on:
      - db

  db:
    image: mariadb:10.3.31
    #    только для v8, позволяет подлкючиться через порт по логину и паролю,
    #    вместо сокета, используемого по умолчанию для версии 8.x.
    #    command: --default-authentication-plugin=mysql_native_password
    working_dir: /var/www
    volumes:
      - ./docker/storage/mysql:/docker-entrypoint-initdb.d
    #      - mysql-data:/var/lib/mysql/data
    ports:
      - ${HOST_MYSQL_PORT}:${DEFAULT_MYSQL_PORT}
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
